name: Add contributors
on:
  push:
    branches:
      - main
jobs:
  add-contributors:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: fregante/setup-git-user@v1
    - name: Add contributors to test2
      run: git subtree add --prefix=test1 https://github.com/basebom/test1.git main
    - uses: BobAnkh/add-contributors@master
      with:
        CONTRIBUTOR: '## Contributors'
        COLUMN_PER_ROW: '6'
        ACCESS_TOKEN: ${{secrets.GITHUB_TOKEN}}
        IMG_WIDTH: '100'
        FONT_SIZE: '14'
        PATH: '/test2/README.md'
        COMMIT_MESSAGE: 'docs(README): update contributors'
        AVATAR_SHAPE: 'round'

