name: Add contributors
on:
  push:
    branches:
      - main
jobs:
  add-contributors:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/checkout@v4
      with:
        repository: basebom/test1
        submodules: true
    - uses: BobAnkh/add-contributors@master
      with:
        REPO_NAME: 'basebom/test1'
        CONTRIBUTOR: '## Contributors'
        COLUMN_PER_ROW: '6'
        ACCESS_TOKEN: ${{secrets.GITHUB_TOKEN}}
        IMG_WIDTH: '100'
        FONT_SIZE: '14'
        PATH: '/test2/README.md'
        COMMIT_MESSAGE: 'docs(README): update contributors'
        AVATAR_SHAPE: 'round'

